
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgoiugsxbpiafytfsfuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnb2l1Z3N4YnBpYWZ5dGZzZnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1Mzk0NzgsImV4cCI6MjA1NzExNTQ3OH0.IzMUhuokFRNj9sp7s_M56VDjoGS10UJcjoc6pXh5gOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
